# Generated by Django 6.0.4 on 2026-04-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=50)),
                ('person_surname', models.CharField(max_length=50)),
                ('person_area', models.IntegerField()),
                ('person_party', models.CharField(choices=[('ANC', 'African National Congress'), ('IFP', 'Inkatha Freedom Party'), ('EFF', 'Economic Freedom Fighter')], max_length=5)),
            ],
        ),
    ]
